version: 2
sources:
  - name: raw
    description: Raw data loaded from NYC Open Data
    database: rabiulhasan-cis-9440-g2
    schema: nyc_proj2_raw_data 
    tables:
      - name: source_mta_ace_violations
        description: |
          This dataset contains records of violations, including issued violations and those rejected for business reasons.
        columns:
          - name: violation_id
            description: Unique identifier assigned for each violation.
            tests:
              - unique
              - not_null
          - name: bus_stop_georeference
            description: Date and time the request was created
          - name: bus_stop_latitude
            description: Date and time the request was closed
          - name: bus_stop_longitude
            description: Agency code
          - name: first_occurrence
            description: Datetime of the first occurrence captured by the first bus.
          - name: last_occurrence
            description: Datetime of the second occurrence captured by the second bus.
          - name: stop_id
            description: The bus stop ID of the closest previous bus stop.
          - name: stop_name
            description: The corresponding bus stop name.
          - name: vehicle_id
            description: Hashed license plate number for the vehicle in violation. Can be used to identify repeat violators.
          - name: violation_georeference
            description: Zip code of the incident location
          - name: violation_id
            description: Street address of the incident
          - name: violation_latitude
            description: Latitude for the bus stop.
          - name: violation_longitude
            description: Longitude coordinate
          - name: violation_status
            description: Event rejection reason or notice/document status.
          - name: violation_type
            description: Bus stop, bus lane, double parked
          - name: bus_route_id
            description: Bus Route ID that the violation occurred on. Some bus routes overlap, see the overview documentation for more information.            
          



      - name: source_nyc_311_traffic
        description: |
          One row per service request.
        columns:
          - name:	agency
            description: Acronym of responding City Government Agency or entity responding to 311 Service Request.          
          - name:	agency_name
            description: Full agency name of responding City Government Agency, or entity responding to 311 service request.
          - name:	bbl
            description: Parcel number that identifies the location of the building or property associated with the service request. The block is a subset of a borough. The lot is a subset of a block unique within a borough and block.
          - name:	city
            description: City of the incident location. In this dataset, City can refer to a borough or neighborhood.
          - name:	borough
            description: This column specifies the borough where the restaurant is located.
          - name:	closed_date
            description: The date and time that an Agency closes a Service Request.
          - name:	community_board
            description: Community boards are local representative bodies.
          - name:	complaint_type
            description: This is the first level of a hierarchy identifying the topic of the incident or condition
          - name:	community_board
            description: Provided by geovalidation.
          - name:	council_district
            description: The City Council district where the service request is located.
          - name:	created_date
            description: Date SR was created
          - name:	cross_street_1
            description: First Cross street based on the geo validated incident location
          - name:	unique_key
            description: Unique identifier of a Service Request (SR) in the open data set
            tests:
              - unique
              - not_null
          - name:	descriptor
            description: Is the restaurant in compliance with the DOHMH health code.
          - name:	cross_street_2
            description: Second Cross Street based on the geo validated incident location
          - name:	incident_address
            description: House number of incident address provided by submitter.
          - name:	incident_zip
            description: Incident location zip code, provided by geo validation..
          - name:	intersection_street_1
            description: First intersecting street based on geo validated incident location
          - name:	intersection_street_2
            description: Second intersecting street based on geo validated incident location
          - name:	landmark
            description: If the incident location is identified as a Landmark the name of the landmark will display here
          - name:	latitude
            description: Geo based Lat of the incident location
          - name:	location_type
            description: Describes the type of location used in the address information
          - name:	longitude
            description: Geo based Long of the incident location
          - name:	open_data_channel_type
            description: Indicates how the SR was submitted to 311. i.e. By Phone, Online, Mobile, Other or Unknown.
          - name:	park_borough
            description: The borough of incident if it is a Parks Dept facility
          - name:	park_facility_name
            description: If the incident location is a Parks Dept facility, the Name of the facility will appear here
          - name:	police_precinct
            description: The NYPD precinct where the service request is located.
          - name:	resolution_action_updated_date
            description: Date when responding agency last updated the SR.
          - name:	resolution_description
            description: Describes the last action taken on the SR by the responding agency. May describe next or future steps.
          - name:	status
            description: Status of SR submitted
          - name:	street_name
            description: Street name of incident address provided by the submitter
          - name:	x_coordinate_state_plane
            description: Geo validated, X coordinate of the incident location.
          - name:	y_coordinate_state_plane
            description: Geo validated, Y coordinate of the incident location.
          - name:	address_type
            description: Type of incident location information available.
          - name:	descriptor_2
            description: This is associated to the Problem 3rd level.
          - name:	vehicle_type
            description: Data provided if service request pertains to a vehicle managed by the Taxi and Limousine Commision (TLC).


